name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/n8acl/freepbx_call_monitor"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "n8acl"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "37777260"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
